[widget]
id = "sysinfo"
name = "Waylestia System Info"
version = "0.1.0"
description = "Real-time system information and performance metrics"
author = "Waylestia Team"
license = "GPL-3.0"
main = "index.html"
icon = "icon.svg"
category = "system"

[display]
width = 480
height = 320
resizable = true
fullscreen = false
always_on_top = false
transparent = false

[permissions]
ipc = true
filesystem = false
network = false
media = false
notifications = false
